--- a/.github/workflows/all-tests-slow.yml
+++ b/.github/workflows/all-tests-slow.yml
@@ -14,4 +14,4 @@
     uses: ./.github/workflows/build-artifacts-and-run-tests.yml
     with:
       matrix_all_combinations: true
-      upload_artifacts: false
+      upload_artifacts: false